### ISSUE TITLE
Add Discord token grabber

### ISSUE THREAD

**Issue by ThomasTubato** [Leaked0/VenomRAT_HVNC-5.0.4.0#2]
could you add the plugin to steal discord tokens via webhook? i tried to do it myself but i don't understand how you wrote some parts of the code. If you do would you by any chance feel like making a video about it so I can see how to modify the project?

**Comment by HideakiAtsuyo** [comment]
> could you add the plugin to steal discord tokens via webhook? i tried to do it myself but i don't understand how you wrote some parts of the code. If you do would you by any chance feel like making a video about it so I can see how to modify the project?

Sorry I'm not working for free, if you want some paid service: DM me on [Discord](https://whois.mrrobot.app/963506730141093909) or [Telegram](https://t.me/HideakiAtsuyo)
